export default {
  INPUT_ANDROID_UNDERLINE: '#eeeeee',
  INPUT_ANDROID_UNDERLINE_FOCUSED: '#CCC',
  title: '#333',
  minimum_text: '#999',
  label: '#999',
  button: '#2E5878',
  backButton: '#FFFFFF',
  buttonText: '#FFF',
  placeholderTextColor: '#CCC',
  errorColor: 'red',
  buttonLoading: '#DDD',
  tabBarIcon: '#B2B2B2',
  tabBarText: '#B2B2B2',
  tabBarIconActive: '#554eb9',
  tabBarTextActive: '#554eb9',
  darkText: '#434343',
  primary: '#4c78d1',
  secondary: '#6f8dc9',
  terciary: '#645',
  quaternary: '#999',
  lighter: '#FFFFFF',
  darker: '#000000',
};
